"""Add Contact Person to Bursary

Revision ID: 76362b3195fb
Revises: e18a95307b75
Create Date: 2024-04-12 13:39:19.731051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76362b3195fb'
down_revision = 'e18a95307b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bursary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person_contact', sa.String(length=12), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bursary', schema=None) as batch_op:
        batch_op.drop_column('contact_person_contact')

    # ### end Alembic commands ###
