"""Refactor Education Model

Revision ID: 97e27a94d004
Revises: 904c15b0f2d0
Create Date: 2024-04-10 15:05:04.522992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97e27a94d004'
down_revision = '904c15b0f2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_type', postgresql.ENUM('primary', 'secondary', 'tetiary', name='institutiontypeenum'), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=False),
    sa.Column('institution_code', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('mode_of_study', sa.String(length=100), nullable=False),
    sa.Column('funding_source', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('education_funding_history')
    with op.batch_alter_table('parent_guardian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_status', postgresql.ENUM('yes', 'no', 'retired', 'self_employed', name='employmentstatusenum'), nullable=False))
        batch_op.drop_column('employed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_guardian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employed', postgresql.ENUM('yes', 'no', 'retired', name='employementstatus'), autoincrement=False, nullable=False))
        batch_op.drop_column('employment_status')

    op.create_table('education_funding_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('institution_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('funding_source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['studentdetails.id'], name='education_funding_history_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='education_funding_history_pkey'),
    sa.UniqueConstraint('id', name='education_funding_history_id_key')
    )
    op.drop_table('education_details')
    # ### end Alembic commands ###
