"""Refactor Docuemnts Table

Revision ID: e18a95307b75
Revises: 1f12e49fea9f
Create Date: 2024-04-12 08:29:56.113138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e18a95307b75'
down_revision = '1f12e49fea9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('document_type', mysql.ENUM('declaration', 'national', 'academic'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('document', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('declaration_documents', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('declaration_documents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaration_documents',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('individual_declaration', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('parent_declaration', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('religious_leader_declaration', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('local_authority_declaration', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='declaration_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('declaration_documents', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.drop_table('documents')
    # ### end Alembic commands ###
